
services:
  local-app:
    build: ./app
    ports:
      - "8501:8501"
    volumes:
      - ./app/db:/app/db

  aws-services:
    build: ./aws
    volumes:
      - ~/.aws:/root/.aws

  oracle-services:  # Placeholder for future
    build: ./oracle